apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: investory
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/spider-su/ops-autopilot.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
