creation_rules:
  - path_regex: secrets[\\/].*\.sops\.ya?ml$
    age: age13ja9yaftagvpgdnyfr7rc3q9ecaatghe6g69gxaafpdp0ef5xd2q7jnhzh
    encrypted_regex: '^(data|stringData)$'
    # The private identity is stored only in the Argo CD decryption boundary.
