apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: investory-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: base-app
  source:
    repoURL: https://github.com/spider-su/ops-autopilot.git
    targetRevision: main
    path: applications/investory
    helm:
      releaseName: investory
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: investory-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
