apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-dev
  namespace: argocd
spec:
  project: base-app
  source:
    repoURL: https://github.com/spider-su/ops-autopilot.git
    targetRevision: dev
    path: applications/postgres
    helm:
      releaseName: postgres
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: postgres-credentials
      namespace: postgres-dev
      jsonPointers:
        - /data

