apiVersion: v1
kind: Service
metadata:
  name: orchestrator-dashboard
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: investory-orchestrator
    app.kubernetes.io/component: dashboard
  ports:
    - name: http
      port: {{ .Values.dashboard.service.port }}
      targetPort: http
