replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

containerPort: 80

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

service:
  port: 80
  targetPort: 80

pvc:
  enabled: false
  storageClassName: proxmox-ceph-rbd
  size: 1Gi
  mountPath: /data

ingress:
  enabled: false
  className: nginx
  host: ""
  path: /
  pathType: Prefix

resourceQuota:
  enabled: true
  hard:
    requests.cpu: "500m"
    requests.memory: "256Mi"
    limits.cpu: "2"
    limits.memory: "512Mi"
    pods: "10"

networkPolicy:
  enabled: true
  extraIngressNamespaces: []
