replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

containerPort: 80

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

probes:
  enabled: true
  startup:
    httpGet:
      path: /
      port: 80
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 12
  readiness:
    httpGet:
      path: /
      port: 80
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  liveness:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 3

service:
  port: 80
  targetPort: 80

pvc:
  enabled: false
  storageClassName: proxmox-ceph-rbd
  size: 1Gi
  mountPath: /data

ingress:
  enabled: false
  className: nginx
  host: ""
  path: /
  pathType: Prefix

resourceQuota:
  enabled: true
  hard:
    requests.cpu: "500m"
    requests.memory: "256Mi"
    limits.cpu: "2"
    limits.memory: "512Mi"
    pods: "10"

networkPolicy:
  enabled: true
  extraIngressNamespaces: []
  externalEgressCidrs: []

pdb:
  enabled: false

topologySpread:
  enabled: true
  maxSkew: 1
  whenUnsatisfiable: ScheduleAnyway
