apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: base-app
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/spider-su/ops-autopilot.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

