apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: base-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  sourceRepos:
    - https://github.com/spider-su/ops-autopilot.git
    - https://kubernetes.github.io/ingress-nginx
    - https://charts.jetstack.io
    - https://metallb.github.io/metallb
    - https://prometheus-community.github.io/helm-charts
    - https://ceph.github.io/csi-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

