apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi-rbd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: base-app
  source:
    repoURL: https://ceph.github.io/csi-charts
    chart: ceph-csi-rbd
    targetRevision: 3.17.0
    helm:
      values: |
        csi:
          kubeletDirPath: /var/lib/rancher/k3s/agent/kubelet
        csiConfig:
          - clusterID: "proxmox-ceph"
            monitors:
              - "192.168.1.51:6789"
              - "192.168.1.52:6789"
              - "192.168.1.53:6789"
        metrics:
          enabled: false
        nodeplugin:
          registrar:
            resources:
              requests:
                cpu: 5m
                memory: 16Mi
              limits:
                cpu: 50m
                memory: 32Mi
          plugin:
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
        provisioner:
          provisioner:
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 64Mi
          attacher:
            resources:
              requests:
                cpu: 5m
                memory: 16Mi
              limits:
                cpu: 50m
                memory: 32Mi
          resizer:
            resources:
              requests:
                cpu: 5m
                memory: 16Mi
              limits:
                cpu: 50m
                memory: 32Mi
          snapshotter:
            resources:
              requests:
                cpu: 5m
                memory: 16Mi
              limits:
                cpu: 50m
                memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: ceph-csi-rbd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

