apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: home-infra-agent-investory-secret
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../home-infra-agent-investory.sops.yaml
