apiVersion: v1
kind: Secret
metadata:
    name: home-infra-agent-solarman
    namespace: home-infra-agent
type: Opaque
stringData:
    app-id: ENC[AES256_GCM,data:NVFvduQEGsLeaYGieyXH,iv:lIyPRUVNp+Bk4+RsRqTAzyNZr7DGp5vc9mF4cHd6INg=,tag:htDj6yIgUBSMQucppXMTUA==,type:str]
    app-secret: ENC[AES256_GCM,data:0kSrFmUFJT4QCQ0R20JGGaVvObY2mrx0o8agBGhPMWg=,iv:txwV3iTVzdn/l8CPUmswmCtt9N55y73596J0EsF0G/0=,tag:ZH6zMnfwJWrU610ZyaEy4w==,type:str]
    email: ENC[AES256_GCM,data:VU5ISFtqoo92UEzRZqmqDG/bM6I=,iv:lyMC9TgL2s0nJGgUm00A83UbDpeSYg2SNKqBOMc+x2E=,tag:PGjWtsbioYqb5ilnblx28g==,type:str]
    password: ENC[AES256_GCM,data:76/wacwfjUwtNnjh7Ig=,iv:rZFeQlEqTdo6+Je6Rni30l9G96EhVDbKWXganEQTS4U=,tag:9smtKCbCudaigrn3rBXBmA==,type:str]
    device-serial: ENC[AES256_GCM,data:5qO7Fy6N7i9vMzr22PCgijYLxgg=,iv:fZeyUu+MGjgx02gN4JPa3m2EnjHLy3Dbj6Zf1Hhhuew=,tag:kdKg4Bp9NSPdoVLc6qcmzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UjR5UnZ5TkJwQmNjYWVS
            OCt5MXJwWHBPZENuQUNZSjIyelhKcktISXdnCnhkOWxQRGlZRHFnSGdiQzZMUVFr
            bEhNSjFlNzhHWkxPT0hYTHErODBINkkKLS0tIGl2K05FVDEzTm96SWt0TE1OZXI3
            d2ZwTjBhTWI2WVRFYk9Nek5xWThqWFUK5uBKD54+wBRA0Tdc9iE4Q9UXa6lx5niR
            gEDnhaOckXL2KWZsw1jLMdQc2lkRb5f23dusv/BBQP/T6TVu3t7RPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1swrrwx043y7h2wemuxvk93fg384ch9f5h8zalj9l4kan5cjduvxstmp0hp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T20:04:25Z"
    mac: ENC[AES256_GCM,data:kd6RyXtWTmLbbNWjiuF9ZFTiHVaJekRaVu/Oi7ElkHmvgA2kopw/sZATXA4Ndi0xNDAFs8BslWB9vsk3kfmgG0GrZHEbyxJTTwH1LcWRtC8LkXKfqkZXgQJgfRuCEp2W5lpwCaAxSJ+ZVOxgjEhR+iTUxFixm2Ffp1ndUfT0B4A=,iv:s5g7zE42PWOuSJ5S2ve4znwFLQzlgZsYgpE1c3KsCTQ=,tag:1J9d8dItR0zqJ3a2IcYJpQ==,type:str]
    version: 3.13.3
