apiVersion: v1
kind: Secret
metadata:
    name: home-infra-agent-investory-db
    namespace: home-infra-agent
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:G3u14g/1mhEbMzH07UNJ2Q/DogIzfPxsb8ux01ucBIrA4DhE9aAYfbKVBvTKrRlMKRvZGnyRQgK4lKizKSRO4ZS1HvwynVZasa6Y5qUX13CUZnzEvwAGShAgtlNLa406ZL3pRDl0LnRGzNCqK2RHrDIW7r3iQZX7r1whORj3sZ+0koe3PNOZZuKc04rhlzSa9xGWQd8MVSdTdZRywuphiR8zVLgGHfN8wJzn9E/njVfDlwazg9UvyFAQc+Y=,iv:H+DVln69op8NOdoP3AMoS1sbcy3M/emEYlxb0uFCKhw=,tag:j6bZBfWZN2MuDDs6Pk/TSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eFJZcGdzM3luQVNVV210
            ZTBQb2dFRHNpNFRZZmJjdytRQXM5Tk4zcXhJClRGTCtLaWN4ZkYraVR6NTA0YUdD
            VG9ZcUVjQm1iODEyOUVHRkQ3REhuZVkKLS0tIFdWYmIxNlJpVzZ4QnR6WnArbUxF
            QnJNN0c5UUdVQkNUeXZCZDdTRFhlZ3MKvDTK4hD0uAHNvoa2wukMNa0RlxLurcc/
            iNhlWJHMT2tfbVlJbdAQefm+M21wc2yyTSWl2NH2HQgsJWdVFEj67A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1swrrwx043y7h2wemuxvk93fg384ch9f5h8zalj9l4kan5cjduvxstmp0hp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T13:23:26Z"
    mac: ENC[AES256_GCM,data:GpnicrYMQ/6pYSoaqE3XmBdkkDTg8aLN5KAqZeSOqK1Gr0DD9l6yQS9XsLIzJwRpqVsOssoXP6M69ri9QvF6Ye7tvKGSvt2t67S6LjgewwPcwEeCnXus65/9pquF9TcXlCrrVxBl9/G/Fp9HywoQhI3nTQuTB+RJ02DHtXnYxPc=,iv:DGLZqyuEwPkz1GDvNEYn/28MKBDnAOrxbUfEKiI1+Sw=,tag:yaj7TDlEs37qYZjL4NFUhA==,type:str]
    version: 3.13.3
