apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:66b1TSvhiSqbaE57,iv:cILC3t3CQvdOLiNIGUKWIxfjZMbTMhsPz9+wQFKXssw=,tag:F1WGEF908zyngFf2Cb2gXA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:5HcANa2OflNw2guc,iv:AVoKzt1zItOwpDNdUY0bZcYa1NSbOBpOLJrTAQWjoYM=,tag:M6in7xLJe/Hos50veH1kvw==,type:str]
    EXCHANGERATE_API_KEY: ENC[AES256_GCM,data:tXvJv8t/FSoP7DOpdQSKNq3xafRHuGhJ2K0LzDRpSKYNm7FZ7wSVl+6HG8Y=,iv:AfsiqriHLl29I2QjvJr8jWbV6MyD0keBWvjYYeNMqts=,tag:13nshsh+5vxj95LLVkY55g==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:rdgXXMmNhkRQDs4e++XF6B/3xHa/tFvMLiUNhPz1xAK0xsu3e/NjpW1jMx4ZEHqU,iv:6tn7ErYJ2Jv+WE6F48AijnpDRttrBAYVtluxjNhVjiY=,tag:DKCiR37c0u1S2reHRptIZg==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:7LsYNViRptiNYqDoqs4mrw5/NHudnR6OQKSFLZlPFnVcFstE3QSP7Mfm22H4+t6sU4hRyftSJQS96fpNLehHyQ==,iv:CSiJsQ1J9D6ndIu8oePwpyEJNlLc905xmgBRmkfX9XA=,tag:aYrSfB/W8hyda8K7/YUqyg==,type:str]
    TWELVEDATA_API_KEY: ENC[AES256_GCM,data:V7iWB/CqGzGpv6SEAV8XJguKLWVK/SyXWHiL/YUcf+x0/tRoIxi/5U4k7sY=,iv:d5hTDEFjwbQzFuutV7LyJdx0i8oB7LpW/+gnJppP7IM=,tag:XdRNtQHklJPLIl8MexTJhQ==,type:str]
kind: Secret
metadata:
    labels:
        app: investory
        app.kubernetes.io/instance: investory
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: investory
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: investory-0.1.0
    name: investory-secrets
    namespace: investory-prod
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdzllWGJqR0pXOTJSSXNK
            Z0ppRFY3ajFLNnd5ZzMzRjI4c0pNbHJXR2p3CjUvOFE1RUpsRi9peTAzcEVPR3ZK
            Wmh4TzRoSkIvdG5OWi9SbDQzb1IrTEUKLS0tIC9VL3RPM0ZPOEU0Yk82RE1ndVBK
            Z2tMNUx6K3lzTURXZC9SaWhiYm0waWMKcfZ19wHv0BBy4tvMV5FrV0lwKIo3IyWP
            YA5DwJ6v1FVdRnba9gcSC3MWv0OuFoPslM5OtJ0JuoNoaY2TY6gKSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13ja9yaftagvpgdnyfr7rc3q9ecaatghe6g69gxaafpdp0ef5xd2q7jnhzh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T09:37:50Z"
    mac: ENC[AES256_GCM,data:rNsT/7C8gF3ZINJiHCuvrZshr1LC00UzxmXF51vQ4tG/grTl0x5zGU55Cy839KFyoMM13e2+t6PgHgDzF5+kZDSYm+QZBNeNP2HugzYlC2GCeEP9cxtDQddqWWv5QeHRM6u39QqndV+VeEBzmegTseJyYzwGYFsZHDM69ufOJuk=,iv:z+BrY6u6lbA01+9lBqltYOV3mXJH/VhIhfXcinz9x2s=,tag:B9ZFAOZ5XnFgk1IaV8quqQ==,type:str]
    version: 3.13.3
