apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:1yRzvLOed/RTrjSj,iv:EQDV1S+puXs+bBpzVglNbeM4fcua2MkHUkhf0XVInzs=,tag:1R22voUK0IVVitIHlFOZBA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:j4XEWzz/KJWq1D8f,iv:j5J2fwTHn5dvtwPla6nXkZuuhm1P/YO68ll8CzU9Xk4=,tag:Hu3o/wwI4ORsvrG0UGdGfw==,type:str]
    EXCHANGERATE_API_KEY: ENC[AES256_GCM,data:4t3kyGLRqc8GuKToDmhm2M9b+/QShIfVTZcX+z/paPG3b3Tq1Om25F+E32g=,iv:V/0JsTBG8paiQegXgxuSB4joW+7YQuHYbO8SX5+cQEA=,tag:8EsouX+2l29uA6ZoKKIlpA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:bA56XCJVqD3oK+G3DvWOVYUfjKuhBXLqg+dRG+CbFjYbrE3Iqa+w7DOHfwFH4e1z,iv:1Xysjh6lOjlDeHlvvA1nFgOyH7ANnwr/6jAtwikZJKY=,tag:b3uOfO3lRu4YK5rRkN4TDQ==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:gXoVMACay6MuW333uQS8Ee9oD8r7BS3Pfl5B7zJraeVHSPyASfZs7o30lCbsvBa05WIIgM4ivoRfRd/jOI3f7A==,iv:g/SKBT0SK0+E/+VEckKtjsAN3IOvB9476RqvCGfgEZY=,tag:px70Lql8GKa1pn0edUzTbg==,type:str]
    TWELVEDATA_API_KEY: ENC[AES256_GCM,data:PNxOjUlQLd5sllJNJ1tY7tcbrb8d9Ne/LKyW6qw67IIFUuMgJL4r0cvKBlk=,iv:HryWOS4kHePAKOKcOe/zJ0hyRY03n7hRHPuaJHDe7yI=,tag:2GtvrvxMu6vTrxKduaDYQQ==,type:str]
kind: Secret
metadata:
    labels:
        app: investory
        app.kubernetes.io/instance: investory
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: investory
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: investory-0.1.0
    name: investory-secrets
    namespace: investory-prod
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMN0VYZmwvY3JFUFRDNEFN
            ZVlBYVpETVNUV1k0bjRmWVBlS280Q1BUelVzCkZadWxtUitScmduU0N6cGg2OFVl
            dDNuWUFaVjhoQ1NyK1JPS2hRSVNuNTQKLS0tIFplYy92S1laMzRHRnJ6U0lTU0Fj
            N285WnB2cFFYcHhnUGJEOFF3ZjRMV2MKVhfw5d3qhhQrdI48RvElXTYS+nzyQHQ4
            1oELGPv/bAymISsBLOCCIJrp2bhN5tJZLTK/veIxANOneeWW4ik6Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1swrrwx043y7h2wemuxvk93fg384ch9f5h8zalj9l4kan5cjduvxstmp0hp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T09:49:46Z"
    mac: ENC[AES256_GCM,data:hlwvaEgIMoJyS3k/e0nS07mx0hM4CNILK0RR2IFjrAfg0SqH9Peop+NsS4YwK1zfIT7gxukqabmHYMiwGjFjxm59n1LYVLHphKeIbJ3KNMi9aO8MLq8mUfcukG/txh7lARA4HZh0lINj/Mb2IiJiEiX40OAkx3EsK8ykK/EOIDc=,iv:bdf7HXur2mfA31KS5gVkNb1nxCpLfTLWeZwbcDeLkLI=,tag:xDTEBK4CYB1V33AISCqJAw==,type:str]
    version: 3.13.3
