apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:AkKhTIdgV9IBTnWX,iv:1GYIDjpdnQcv1m11y2rMveo+roSJaXvPJPNehtBqrZo=,tag:YhQS6n3D/asU9dPQzuui5w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1BI+iYcX1x51Rndm,iv:XfzaO/Ka0fNXl6e4fjxhM5i4NiaM1j5Dxti0jkCitQs=,tag:uMzcCGkdU1gtCxyFbU3GSg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:g8hQBZ0ZWSJTmNmq,iv:12jSveGD4BxIExJMgMkBOc7lvJ5E5mFHhTJZ4c2vF+E=,tag:2LrlEZ+OA/ZShEGTRxSklA==,type:str]
kind: Secret
metadata:
    labels:
        app: postgres
        app.kubernetes.io/instance: postgres
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgres
        app.kubernetes.io/version: "16"
        helm.sh/chart: postgres-0.1.0
    name: postgres-credentials
    namespace: postgres
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WXJ1U3lTR1E5aS84Vkt5
            OHNRVlFMSkw2K0xVY0hTZi9xWXFWdDB2a3hnCmVxYjlGVm53cmQ0aUFYT2Qydlp5
            T3luRWtDUXFzSisvWVVNTDdqdmtISXcKLS0tIHNSRUxvUnpyWkdsdngwMllYUXFi
            NDNZQzVnU0Y2ZEV0aE1GTE5lL3VqUHcK45alugumc7KR5ldxQPPEDRj6bhJX6/ie
            fKtQi994G34WfZE8zPuevjFYqnjSs6+AIUe9LsTFKD8zAfndf4Cr5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13ja9yaftagvpgdnyfr7rc3q9ecaatghe6g69gxaafpdp0ef5xd2q7jnhzh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T09:37:50Z"
    mac: ENC[AES256_GCM,data:T2Ev0ddEpsJM+LMuwYmw5D7t1iFDDTSiWV5e8raih3YWPm4u7BisUVhRg87S/1brnZQARpA7CND6u9gEn1eD7yaoIQfUQRJpWuE7GDI6LT7aGTiTeY513lTKvMcHKjPK4h2OFQFjFGvfhKObwNQsdtKPkScLjjD8XXyTJnyt00o=,iv:LUENVdQUS8KIJWDVPp6NciBB2CNxsQtVt+al+R8qzg0=,tag:KcjdKqDMJQQ73UYlQnciKA==,type:str]
    version: 3.13.3
