apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:8kUVX661d3HSZKfr,iv:YjaDD3/3SZ1ER+yzuvonQBn3fSHe20nWlUMpXvk2gzc=,tag:RZ75QmkWo13p9ORxX+PZTA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PIyU+Q1x2/fVqZY0,iv:TtUFm0MF7oV+/DMnX8YLJJtIsMFRDFwW6QolqRYPFXE=,tag:R3W1esGOuHc09q2OzOXQgQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:yJbsOfYye44m9Pcb,iv:xPW8R6lhL+0YWVy0GciVJuG8bIBdxVNGnGDwXyqcNg0=,tag:+GQqCwI16889WX14vNpf/w==,type:str]
kind: Secret
metadata:
    labels:
        app: postgres
        app.kubernetes.io/instance: postgres
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgres
        app.kubernetes.io/version: "16"
        helm.sh/chart: postgres-0.1.0
    name: postgres-credentials
    namespace: postgres
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTWtzbC9kQ2dnU1F0OWZp
            T1ZnNXRPWFlIT2Z4eXRLRURWVXg1b2RpcEVvCklnRkN6dnU5N0tOWmhGNUsveEYw
            eEE1bm1GMjI0UnBsRDQ0THZIQ3E3OEkKLS0tIHQ0WTlCbElRZlN6NUszTWNVYzhU
            andqTm5uTzY5aFdnWWEvZ1pPOXdyZncKdxVXkVq+60kAAgwR0qsHr6ES2O1tjG6t
            iZg18pu9DpGpCLy99cZsKLjkbV/Pg5w+i2+pZbrOIwHH1RSkE8dz5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1swrrwx043y7h2wemuxvk93fg384ch9f5h8zalj9l4kan5cjduvxstmp0hp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T09:49:46Z"
    mac: ENC[AES256_GCM,data:LFjXNWVHU0C0vDqFDgVtfSFIfPDVMbbcb1pe27ie43BDu2Ack+OzGfiYxRt/fi8Cet4aAgAPImyMFxBTvodkrPrxEIkfmFQYPQHkf12mqNMBZ+FPnTBQ5Kmvb+qrk8ZfhprFpuHQ+mM8grtGZfvWDhweyN2J2o5C6R0gclGxVvo=,iv:ENuM0ZTO7V1zhFN5E9MlHaqEkF9MC902wuQKhouVvnQ=,tag:BH6h7Nw9/m2YNcqKPtLftA==,type:str]
    version: 3.13.3
