apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: workload-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - postgres-credentials.sops.yaml
  - investory-secrets.sops.yaml
