apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: investory
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spider-su/ops-autopilot.git
    targetRevision: main
    path: apps/investory
  destination:
    server: https://kubernetes.default.svc
    namespace: investory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
