apiVersion: v1
data:
    smtp-password: ENC[AES256_GCM,data:+HwjmIcRe4g14ccyGL8pGO6oyuh5mMlK9EsJSg==,iv:BmsvK+5W5eAF8DKEm5W/MZJKXnkTnlCyzp5GUX+zLt4=,tag:XcSCs3KZHjhntogVxi3DkA==,type:str]
kind: Secret
metadata:
    name: alertmanager-smtp
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbkJBcWUvajRoNG1GV2VM
            aVhHK0loa3hidFpxZ0NqT0ZVa05rUmdKRVdBCmVsT2F0UlVobzBmeVIxMGFKelh3
            azBmR1plUHF4Ym0zNzhuVzZFc2ZMKzQKLS0tIGlvcUVlVDBXeG0ycCs2TWZPTjVu
            Qlp2Y2dtamNWcmx5a3B0MU93UHFXcWMK++FwOS9R3sHn+yGXHds6De4vuT6u7x7k
            OqN9PyhRAS61r7MRWOvFTI9AxRCNdZ8Wz0PjTmHXCZbDzRfjl70y/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1swrrwx043y7h2wemuxvk93fg384ch9f5h8zalj9l4kan5cjduvxstmp0hp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T09:49:46Z"
    mac: ENC[AES256_GCM,data:WJQa2ADTILOXiLcs9IzMZQXD41sv3Lbj+mAlurTtZMmOumoH4YLViIRIAyLQMV0EGg8Z68xx0kdEG6qSVcw8+uBiwb9c1CYpwptqLmOAlzRvRmM/1uz/g69eOav8bzxdiS5Crhwg0WRptRMjwieDPnhKPJUQJ4HoQfURV7sKPUw=,iv:IJNPS8zP9flbiSZv8ppuIuIwo7P5Kx2BKgobMPpH3UA=,tag:v1TBzVqHrd0tzKyv5V0IQg==,type:str]
    version: 3.13.3
