apiVersion: v1
data:
    smtp-password: ENC[AES256_GCM,data:TPPJOrIUn1IpVZ2PYz0Z3TRhPCeqJbYqyqKU6w==,iv:ZpDO5DqxH1n7QC3Ze/FI4krqH4kg2qqIZ47nH01wIq4=,tag:HwPfg4nctcAGMWKn/F4AfA==,type:str]
kind: Secret
metadata:
    name: alertmanager-smtp
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUkFEaGNMYlNXMENxTHVw
            dkVZV3FMdmYwcml2Wm9kWklFNWxNRXpHUFRjCi9udHp6aVgyYlliaGE5NTgxb3J5
            ZDk4TVI4ZmZyMDRWRlQyQnF1U0V1a00KLS0tIFc2OFI1cDN0MFpQU2tNMlBDUWx4
            Nzl2dDRQRUdkR0szT3FhekVNNkszS0EKuzxkr7BUPJFe4zqaNzJTowHkkblqUV4T
            ipYulithrEuFvpsa3EHYsRPH/cGtvB0yPn/6txEn/3aao46k2e8gxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13ja9yaftagvpgdnyfr7rc3q9ecaatghe6g69gxaafpdp0ef5xd2q7jnhzh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T09:37:49Z"
    mac: ENC[AES256_GCM,data:1bd67zjoJZfJwW+zwURBp0zK0tXSx+aI7Y5f6fiB0mr2vaqdMeMJChWrahmaO4hBCnWYBckCWOC2gEvioUWohWtlB+YiYmPjMHu1fnSLsoQ81WnhVyuThi+qhSKbFZ+7IUFmazeZHhq9Fw5Ela1NWNp5hTwuKf5OFW675yMP6Jg=,iv:h1CIFYav2y2FI5r9TlOgUGid87Rq7Y/MXF0RemSAGoE=,tag:Qi5k9jT05VuzZqKr3sN1Dw==,type:str]
    version: 3.13.3
