apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:Pg/tKm+sReE=,iv:v+XOD0QcMob7ZD1sqmU0IZtHsF5jM/WtdML4AQYuya8=,tag:cbWH4Vkvy28cFFl8VS/DvA==,type:str]
    userKey: ENC[AES256_GCM,data:2QCRSwZjHQKeuLQ+XcgWXe2bobQOhEAVa7z2b1V99L440Z+U/ydm5YrF09Jpnf1bpl13myk3cRI=,iv:hffd/0cMiBa647zPd3WxgYIpZOhiDeLORf6P+NfrN64=,tag:iqlAaBZ7zzz2hKII5NEU6A==,type:str]
kind: Secret
metadata:
    name: ceph-csi-secret
    namespace: default
type: kubernetes.io/rbd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOFVScmowSXJyMWNhZUty
            dG1jeVlUQkZpZlBDWElPRkdiR2R5cVpBQkZJCkZVZm1tKytPbjhhNW95endXY21T
            KzNoMGVIZzExK0FYOGtLbjFhc0d2aXcKLS0tICtFVHJGbitqZWNOY3Z6dHdsVkhJ
            ejJ5YTlva29hMWxhMmdNNExUUWMydDQKHRZUzj/mi4ekMikYjlz3ugV3WRYdNhKl
            R0hhx5qbRqXEfAyLSxJd+v0zk9AKMGARik13Q4GMnz/QHNf7GB3DYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13ja9yaftagvpgdnyfr7rc3q9ecaatghe6g69gxaafpdp0ef5xd2q7jnhzh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T09:37:49Z"
    mac: ENC[AES256_GCM,data:kunB4COD/uoM5K1nVsoLG3QaHImoJam91jFGIRjsW+m1AKdK/r7MpwQ5Wm71BYRsE4LJOS2pVyGjv8OJNuzoHF0sPO3l8UawLSoK8RjVD2lqgo8bdoY5/Vn9Ry3quNA4vQBMKRfn3p1W1FytLqTNK6IPE2wGHk45lYIObpX+KCQ=,iv:gMFB5/9PEgHVNC9IYqCKZn5HR4vHR8OrNWWaWz1/RKM=,tag:uPJFJC6bH6VQTu6Pu7TOXg==,type:str]
    version: 3.13.3
