apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:HcDWkQxJG5Q=,iv:fOrZrIFj4CS0LxQna5X6ps/NIjtzwZi9dMnSFOpJt6M=,tag:Ruzr34QSyIOSwDd6C01n5w==,type:str]
    userKey: ENC[AES256_GCM,data:wQn7Xo0bAieldtjVevsz76qP+pypEQjmUctY4vQ/fYvtGGmBJaSCpAWi+APxffOuuphE51HKjrE=,iv:jaIqi62uq3DYgMNKPIuFJmJEjFStmBUSMMTsG4t8Qss=,tag:rXHjhYmN64LQe853o4SSJQ==,type:str]
kind: Secret
metadata:
    name: ceph-csi-secret
    namespace: default
type: kubernetes.io/rbd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cnM0bnhEcGNLdUtDR00r
            YVR6akVQeDZnMXBnK3ArcTRndmdtVHJmV1NFCndoV0EyaU5Nbmo4aVdCbVJsYzVy
            M3pMZ1ArdXNZYWM0MUxvVzh2bENNZzAKLS0tIHhRM1I3QmdaeXFmYURpbHdaOE9X
            WEVnRXA0RlFzWFFBRlIxbmZoSHduYlUK7OWtlv8caFAh6VfTfQh7Gm355EIj+OF2
            2KyQNQBLeJA+0jbeT6whdIfDdDPPdQguU2ZzHkJq6m6Io0TgXNlj+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1swrrwx043y7h2wemuxvk93fg384ch9f5h8zalj9l4kan5cjduvxstmp0hp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T09:49:46Z"
    mac: ENC[AES256_GCM,data:701EQXXi8Ceu9N/9sXJS4RbAVL11ffNOgo6jrDTDGXV9xXLE1BBvjBMubhMXU0AL44fCU+/QIRUZcAifkqq+r6xPRfzyFepPphhUCX5QQM6gcFy6hHFKJ8z4CEJI9Yehg0PHwpWAF6MhZROy41GCptRb06C+ojC3pvUSc2mbu8c=,iv:N1IkbAB2gASGrgfL2r1jqmV7eERrUOWI1YTDgPysSuw=,tag:GRDceCMBOVXZ0x+bM2S2tQ==,type:str]
    version: 3.13.3
