apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-ceph-rbd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rbd.csi.ceph.com
parameters:
  adminid: admin
  clusterID: proxmox-ceph
  csi.storage.k8s.io/node-stage-secret-name: ceph-csi-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: ceph-csi-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  imageFeatures: layering
  imageFormat: "2"
  monitors: 192.168.1.51:6789,192.168.1.52:6789,192.168.1.53:6789
  pool: home-pool
  userid: admin
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - discard
